---
  .travis.yml:
    hc_secure: "hFn1IPniahB7mdgd0l8rRjeCfkkAWnSNJA5PkKaWKtv/e+JWkFp6mIsdPV+XipLL+h8f6GfNvvwHQtWHTWVQHbEszVxL4nGzIeBI391nyHFZR9vU3ePy2rkm3dlm90NM59XVYMaGBJBoIyAmLOoFZZhx0OgIWKQ73HFpkZOdyv8="

